# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Enablon Response' do
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

pod 'Eureka', '~> 4.3.1'
pod 'Firebase/Core'
pod 'Firebase/Firestore'

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Enablon Response

end
